### ISSUE TITLE
Add Activity Form

### ISSUE THREAD

**Issue by ajd3187** [trice7/Sustainable-Routes-Client#6]
Make a form to add Activities.

- [x] add Activity name
- [ ] Add Destination drop-down allows the user to select from our predetermined destinations
- [x] Add the Activity destination
- [x] Select as Favorite
- [x]  Add Activity Button

**Comment by tatianabarga** [comment]
- [x]  form displays
- [ ]  form has all relevant and working inputs
- [ ]  form submits
- [ ]  form adds to database
