### ISSUE TITLE
Add/Edit Activity Form

### ISSUE THREAD

**Issue by ajd3187** [trice7/Sustainable-Routes-Client#9]
Create a form that can create new Activities and change existing ones.

- [x] name of activity 
- [x] description 
- [x] destination(drop down)
- [x] tags(drop down)

![image](https://github.com/trice7/Sustainable-Routes-Client/assets/56607840/dfb7b815-1fac-4317-894b-31ca5aa72557)

**Comment by tatianabarga** [comment]
- [x] form displays
- [x] form has all relevant and working inputs
- [ ] form submits 
- [ ] form updates database
- [ ] form adds to database
